services:
  - type: web
    name: ryugym-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_ORIGIN
        value: https://amancodexd.github.io
      - key: ESEWA_PRODUCT_CODE
        value: EPAYTEST
      - key: ESEWA_SECRET_KEY
        value: "8gBm/:&EnhH.1/q"
      - key: ESEWA_PAYMENT_URL
        value: https://rc-epay.esewa.com.np/api/epay/main/v2/form
      - key: ESEWA_STATUS_URL
        value: https://rc.esewa.com.np/api/epay/transaction/status/
      - key: BACKEND_PUBLIC_URL
        value: https://ryugym-api.onrender.com
